arasunu/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from climatologies.views import Weather

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('departments.urls', namespace='departments')),
    url(r'^', include('climatologies.urls', namespace='climatologies')),
    url(r'^', include('locations.urls', namespace='locations')),
    url(r'^', include('hydrologies.urls', namespace='hydrologies')),
    url(r'^', Weather, name='weather'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

climatologies/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^history/$', views.History, name='history'),
    url(r'^api/v1/json/$', views.ClimaJson, name='climaJson'),
    url(r'^api/v2/json/$', views.ClimaJson2, name='climaJson2'),
    url(r'^api/v4/json/$', views.get_cli, name='get_cli'),
    url(r'^api/v3/json/(?P<city>[\w]+)/(?P<month>[0-9]+)/(?P<year>[0-9]+)/$', views.ClimaJson3, name='climaJson3'),
    url(r'^graphic/$', views.Graphic, name='graphic'),
    url(r'^graphic/form/$', views.getForm, name='getForm'),
    url(r'^graphic/form/c3/$', views.getFormc3, name='getFormc3'),
    url(r'^ajax/year/$', views.climaParam, name='climaParam'),
]

climatologies/models.py
# coding=utf-8

from __future__ import unicode_literals

from django.db import models
from stationtypes.models import StationType
from locations.models import Location
from stations.models import Station

class Climatology(models.Model):
    id_estacion = models.ForeignKey(Location, on_delete=models.CASCADE)
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    id_tipo = models.ForeignKey(StationType, on_delete=models.CASCADE)
    nombre_estacion = models.CharField(max_length=60, blank=True, null=True)
    fecha = models.DateTimeField(blank=True, null=True)
    tmax = models.CharField(max_length=10, blank=True, null=True)
    tmin = models.CharField(max_length=10, blank=True, null=True)
    tmed = models.CharField(max_length=10, blank=True, null=True)
    td = models.CharField(max_length=10, blank=True, null=True)
    pres_est = models.CharField(max_length=10, blank=True, null=True)
    pres_mar = models.CharField(max_length=10, blank=True, null=True)
    prcp = models.CharField(max_length=10, blank=True, null=True)
    hr = models.CharField(max_length=10, blank=True, null=True)
    helio = models.CharField(max_length=10, blank=True, null=True)
    nub = models.CharField(max_length=10, blank=True, null=True)
    vmax_d = models.CharField(max_length=10, blank=True, null=True)
    vmax_f = models.CharField(max_length=10, blank=True, null=True)
    vmed = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return "%s" %(self.nombre_estacion)

    class Meta:
        verbose_name = 'Climatología'
        verbose_name_plural = 'Climatologias'

climatologies/forms.py
from django import forms
from cities.models import City
from datetime import datetime

class FormSearch(forms.Form):
    n = tuple((str(n), str(n)) for n in range(1973, datetime.now().year + 1))
    city_list = City.objects.all().order_by('nombre')
    text = forms.ChoiceField(choices=((x.nombre, x.nombre) for x in city_list ), error_messages={'required': 'Este campo es obligatorio'})
    fecha = forms.ChoiceField(choices=n, error_messages={'required': 'Este campo es obligatorio'})

class FormGraphic(forms.Form):
    city_list = City.objects.all().order_by('nombre')
    c = ((x.nombre, x.nombre) for x in city_list )
    c = tuple([(u'', '------')] + list(c))
    text = forms.ChoiceField(choices=c, error_messages={'required': 'Este campo es obligatorio'})
    n = tuple((str(n), str(n)) for n in range(1973, datetime.now().year + 1))
    months = [('1','Enero'),
                  ('2','Febrero'),
                  ('3','Marzo'),
                  ('4','Abril'),
                  ('5','Mayo'),
                  ('6','Junio'),
                  ('7','Julio'),
                  ('8','Agosto'),
                  ('9','Setiembre'),
                  ('10','Octubre'),
                  ('11','Noviembre'),
                  ('12','Diciembre'),]
    months = tuple([(u'', '------')] + list(months))
    month = forms.ChoiceField(choices=months, error_messages={'required': 'Este campo es obligatorio'})
    n = tuple([(u'', '------')] + list(n))
    year = forms.ChoiceField(choices=n, error_messages={'required': 'Este campo es obligatorio'})

climatologies/views.py
# -*- coding: utf-8 -*-

from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .forms import FormSearch, FormGraphic
from .models import Climatology
import json
from django.http import JsonResponse
from django.core.serializers.json import Serializer

def History(request):
    title = 'Arasunu'
    text = 'Busqueda de historicos de temperatura'
    template = loader.get_template('history.html')
    if request.method == 'POST':
        form = FormSearch(request.POST)
        search = request.POST['text']
        fecha = request.POST['fecha']
        if form.is_valid():
            object_list = Climatology.objects.filter(id_estacion_id__id_ciudad__nombre__icontains=search, fecha__year=fecha).order_by('-fecha')
            context = {
                'title': title,
                'text': text,
                'form': form,
                'object_list': object_list,
            }
            return HttpResponse(template.render(context, request))
    else:
        form = FormSearch()
    context = {
        'title': title,
        'text': text,
        'form': form,
    }
    return HttpResponse(template.render(context, request))

def Weather(request):
    title = 'Arasunu'
    template = loader.get_template('weather.html')
    context = {
        'title': title,
    }
    return HttpResponse(template.render(context, request))

def ClimaJson(request):
    object_list = Climatology.objects.filter(id_estacion_id__id_ciudad__nombre__icontains='Luque', fecha__year=2013).order_by('fecha')[:5]
    data = [{str(item.station.location.id_ciudad.nombre): item.tmax} for item in object_list]
    data1 = {'comidas': data }
    return HttpResponse(json.dumps(data, ensure_ascii=False, encoding="utf-8"), content_type='application/json')

def get_cli(request):
    cli = Climatology.objects.filter(id_estacion_id__id_ciudad__nombre__icontains='Luque', fecha__year=2013).values('tmax', 'tmin').order_by('fecha')[:5]  # or simply .values() to get all fields
    cli_list = list(cli)  # important: convert the QuerySet to a list object
    return JsonResponse(cli_list, safe=False)

def ClimaJson2(request):
    object_list = Climatology.objects.filter(id_estacion_id__id_ciudad__nombre__icontains='Luque', fecha__year=2013).order_by('fecha')[:5]
    data = [{'Letter': item.tmax, 'Freq': item.tmin} for item in object_list]
    return HttpResponse(json.dumps(data, ensure_ascii=False, encoding="utf-8"), content_type='application/json')

def ClimaJson3(request, city, month, year):
    object_list = Climatology.objects.filter(id_estacion_id__id_ciudad__nombre__icontains=city, fecha__month=month,  fecha__year=year).order_by('fecha')
    data = [{'Letter': int(item.fecha.day), 'Freq': item.tmax} for item in object_list]
    return HttpResponse(json.dumps(data, ensure_ascii=False, encoding="utf-8"), content_type='application/json')

def Graphic(request):
    title = 'Arasunu'
    template = loader.get_template('graphic.html')
    context = {
        'title': title,
    }
    return HttpResponse(template.render(context, request))


# def climaParam(request):
#     year = request.GET.get('year', None)
#     text = request.GET.get('text', None)
#     data = {
#         'is_taken': Climatology.objects.filter(id_estacion_id__id_ciudad__nombre__icontains=text, fecha__year=year).exists()
#     }
#     return JsonResponse(data)

def climaParam(request):
    text = request.GET.get('text', None)
    month = request.GET.get('month', None)
    year = request.GET.get('year', None)
    data = {
        'city': text,
        'month': month,
        'year': year
    }
    return HttpResponse(json.dumps(data, ensure_ascii=False, encoding="utf-8"), content_type='application/json')
    # return HttpResponse(dump, content_type='application/json')
    # object_list = Climatology.objects.filter(id_estacion_id__id_ciudad__nombre__icontains=text, fecha__year=year, fecha__month=month).order_by('fecha')
    # data = [{'Freq': item.tmin, 'Letter': item.tmax} for item in object_list]
    # return HttpResponse(json.dumps(data, ensure_ascii=False, encoding="utf-8"), content_type='application/json')

def getForm(request):
    title = 'Arasunu'
    form = FormGraphic()
    template = loader.get_template('formcopy.html')
    context = {
        'title': title,
        'form': form,
    }
    return HttpResponse(template.render(context, request))

def getFormc3(request):
    title = 'Arasunu'
    template = loader.get_template('formc3.html')
    context = {
        'title': title,
    }
    return HttpResponse(template.render(context, request))

# def ClimaJson(request):
#     records = Climatology.objects.filter(id_estacion_id__id_ciudad__nombre__icontains='Luque', fecha__year=2013).order_by('fecha')[:5]
#     json_res = []
#     for record in records:
#         json_obj = dict(
#             data = record.tmax,
#         )
#         json_res.append(json_obj)
#     return HttpResponse(json.dumps(json_res), content_type='application/json')

# def ClimaJson(request):
#     data = MySerializer().serialize(Climatology.objects.filter(id_estacion_id__id_ciudad__nombre__icontains='Luque', fecha__year=2013).order_by('fecha')[:5], fields=('tmax'))
#     return HttpResponse(data)
#     # return HttpResponse(json.dumps(data, ensure_ascii=False, encoding="utf-8"), content_type='application/json')

# class MySerializer(Serializer):
#     internal_use_only = False
#     def get_dump_object(self, obj):
#         data = super(MySerializer, self).get_dump_object(obj)
#         newdata = {}
#         newdata.update(data['fields'])
#         # newdata['pk'] = data['pk']
#         return newdata

# list_checkin = Userinfo.objects.filter(userid=pkuser, check__userid=pkuser, check__checktime__month=month, check__checktime__year=year).values('check__checktime').order_by('check__checktime')

climatologies/templates/form.html
{% extends 'layout.html' %}
{% load widget_tweaks %}

{% block title %}
    {{ title }}
{% endblock %}

{% block header %}
    {{ title|upper }}
{% endblock %}

{% block javascript %}
<script>

    // $("#id_text").change(function () {
    //   console.log( $(this).val() );
    // });

    // $("#id_year").change(function () {
    //   console.log( $(this).val() );
    // });

    // $("#id_year").change(function () {
    //   var year = $(this).val();
    //   // var text = $(this).val();
    //   var text = $("#id_text").val();
    //   // console.log(year);

    //   $.ajax({
    //     url: "{% url 'climatologies:climaParam' %}",
    //     data: {
    //       'text': text,
    //       'year': year
    //     },
    //     dataType: 'json',
    //     success: function (data) {
    //       if (data.is_taken) {
    //         alert("El dato existe"+ "-" + text);
    //       }
    //     }
    //   });

    // });
</script>
<script src="http://d3js.org/d3.v3.min.js"></script>
<script>

    $("#id_text").change(function () {
      console.log( $(this).val() );
    });

    $("#id_year").change(function () {
      console.log( $(this).val() );
    });
    $("#id_month").change(function () {
      console.log( $(this).val() );
    });

    $("#id_year").change(function () {
      var year = $(this).val();
      var text = $("#id_text").val();
      var month = $('#id_month').val();

      $.ajax({
        url: "{% url 'climatologies:climaParam' %}",
        data: {
          'text': text,
          'month': month,
          'year': year
        },
        dataType: 'json',
        success: function (data) {
            for(i = 0; i< data.length; i++){
              $('#result').append('<p>'+data[i]['letter']+ ' ' + data[i]['freq']+ '</p>');
            }
            data = JSON.stringify(data);
            console.log(data);
        }
      });

    });
</script>
{% endblock %}

{% block content %}
  <form method='post' class="navbar-form navbar-left">
      {% csrf_token %}
      <div class="form-group">
        {% render_field form.text class="form-control" %}
        <strong class="text-danger"> {{ form.text.errors }} </strong>
      </div>
      <div class="form-group">
        {% render_field form.month class="form-control" %}
        <strong class="text-danger"> {{ form.month.errors }} </strong>
      </div>
      <div class="form-group">
        {% render_field form.year class="form-control" %}
        <strong class="text-danger"> {{ form.year.errors }} </strong>
      </div>
  </form>
  <div id="result"></div>
{% endblock %}

climatologies/templates/formc3.html
<!DOCTYPE html>
<html>

<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <title>Datos en tiempo real con D3</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link href="{% static 'css/c3.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/stylesc3.css' %}" rel="stylesheet" type="text/css">

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="http://d3js.org/d3.v3.min.js"></script>
    <script src="{% static 'js/c3.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>
    <!-- My script -->
</head>

<body>
    <div class="center">
        <div class="voteApp">
            <div class="container">
                <div class="comida">
                    <button id="tacos" type="button" class="btn btn-primary btn-lg">Tacos</button>
                    <p id="votos_tacos" class="bg-info">
                        <span class="badge">0</span>
                        <br> votos
                    </p>
                </div>
                <div class="comida">
                    <button id="paella" type="button" class="btn btn-success btn-lg">Paella</button>
                    <p id="votos_paella" class="bg-info">
                        <span class="badge">0</span>
                        <br> votos
                    </p>
                </div>
                <div class="comida">
                    <button id="ceviche" type="button" class="btn btn-info btn-lg">Ceviche</button>
                    <p id="votos_ceviche" class="bg-info">
                        <span class="badge">0</span>
                        <br> votos
                    </p>
                </div>
                <div class="comida">
                    <button id="mangu" type="button" class="btn btn-warning btn-lg">Mangú</button>
                    <p id="votos_mangu" class="bg-info">
                        <span class="badge">0</span>
                        <br> votos
                    </p>
                </div>
            </div>
            <div id="total">
                <span class="badge">0</span>
                <br> Total de votos emitidos
            </div>
        </div>
    </div>
</body>

</html>

climatologies/templates/formcopy.html
{% extends 'layout.html' %}
{% load widget_tweaks %}

{% block title %}
    {{ title }}
{% endblock %}

{% block header %}
    {{ title|upper }}
<style>

  .bar{
    fill: steelblue;
  }

  .bar:hover{
    fill: brown;
  }

    .axis {
      font: 10px sans-serif;
    }

    .axis path,
    .axis line {
      fill: none;
      stroke: #000;
      shape-rendering: crispEdges;
    }

</style>
{% endblock %}

{% block javascript %}
<script src="http://d3js.org/d3.v3.min.js"></script>
<script>

    $("#id_text").change(function () {
      console.log( $(this).val() );
    });

    $("#id_year").change(function () {
      console.log( $(this).val() );
    });
    $("#id_month").change(function () {
      console.log( $(this).val() );
    });

    $("#id_year").change(function () {
      $('#result').html('');
      var year = $(this).val();
      var text = $("#id_text").val();
      var month = $('#id_month').val();

      $.ajax({
        url: "{% url 'climatologies:climaParam' %}",
        data: {
          'text': text,
          'month': month,
          'year': year
        },
        dataType: 'json',
        success: function (data) {
            // for(i = 0; i< data.length; i++){
            //   $('#result').append('<p>'+data[i]['Letter']+ ' ' + data[i]['Freq']+ '</p>');
            // }
            // data = JSON.stringify(data);
            data = "http://192.168.1.125/api/v3/json/"+data.city+"/"+data.month+"/"+data.year+"/"
            console.log(data);
            graphic(data);

            // var p = d3.select("body").selectAll("p")
            //    .data(data)
            //    .enter()
            //    .append("p")
            //    .text(function (d,i) {return i;});

            /* --------------------------------------- */
            }
      });

    });


function graphic(data){

    // set the dimensions of the canvas
    var margin = {top: 20, right: 20, bottom: 70, left: 40},
        width = 600 - margin.left - margin.right,
        height = 300 - margin.top - margin.bottom;


    // set the ranges
    var x = d3.scale.ordinal().rangeRoundBands([0, width], .05);

    var y = d3.scale.linear().range([height, 0]);

    // define the axis
    var xAxis = d3.svg.axis()
        .scale(x)
        .orient("bottom")


    var yAxis = d3.svg.axis()
        .scale(y)
        .orient("left")
        .ticks(10);


    // add the SVG element
    var svg = d3.select("#result").append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom)
      .append("g")
        .attr("transform", 
              "translate(" + margin.left + "," + margin.top + ")");


    // load the data
    d3.json(data, function(error, data) {

        data.forEach(function(d) {
            d.Letter = d.Letter;
            d.Freq = +d.Freq;
        });
        
      // scale the range of the data
      x.domain(data.map(function(d) { return d.Letter; }));
      y.domain([0, d3.max(data, function(d) { return d.Freq; })]);

      // add axis
      svg.append("g")
          .attr("class", "x axis")
          .attr("transform", "translate(0," + height + ")")
          .call(xAxis)
        .selectAll("text")
          .style("text-anchor", "end")
          .attr("dx", "-.8em")
          .attr("dy", "-.55em")
          .attr("transform", "rotate(-90)" );

      svg.append("g")
          .attr("class", "y axis")
          .call(yAxis)
        .append("text")
          .attr("transform", "rotate(-90)")
          .attr("y", 5)
          .attr("dy", ".71em")
          .style("text-anchor", "end")
          .text("Temperatura");


      // Add bar chart
      svg.selectAll("bar")
          .data(data)
        .enter().append("rect")
          .attr("class", "bar")
          .attr("x", function(d) { return x(d.Letter); })
          .attr("width", x.rangeBand())
          .attr("y", function(d) { return y(d.Freq); })
          .attr("height", function(d) { return height - y(d.Freq); });

    });
}
</script>
{% endblock %}
{% block content %}
  <form method='post' class="navbar-form navbar-left">
      {% csrf_token %}
      <div class="form-group">
        {% render_field form.text class="form-control" %}
        <strong class="text-danger"> {{ form.text.errors }} </strong>
      </div>
      <div class="form-group">
        {% render_field form.month class="form-control" %}
        <strong class="text-danger"> {{ form.month.errors }} </strong>
      </div>
      <div class="form-group">
        {% render_field form.year class="form-control" %}
        <strong class="text-danger"> {{ form.year.errors }} </strong>
      </div>
  </form>
  <div id="result"></div>
{% endblock %}

climatologies/templates/graphic.html
{% extends 'layout.html' %}
{% load widget_tweaks %}

{% block title %}
    {{ title }}
{% endblock %}

{% block header %}
    {{ title|upper }}
{% endblock %}

{% block content %}
    <script src="http://d3js.org/d3.v3.min.js"></script>
    <script>
        d3.json("http://192.168.1.125/api/v1/json/", function (data){
            var canvas = d3.select("body").append("svg")
                .attr("width", 500)
                .attr("height", 500)
            canvas.selectAll("rect")
                .data(data)
                .enter()
                    .append("rect")
                    .attr("width", function (d) { return d.data * 10; })
                    .attr("height", 48)
                    .attr("y", function (d, i) { return i * 50; })
                    .attr("fill", "blue");
            canvas.selectAll("text")
                .data(data)
                .enter()
                     .append("text")
                     .attr("fill", "white")
                     .attr("y", function (d, i) { return i * 50 + 24; })
                     .text(function (d) { return d.data+'°'; })
        })
    </script>

{% endblock %}

climatologies/templates/history.html
{% extends 'layout.html' %}
{% load widget_tweaks %}

{% block title %}
    {{ title }}
{% endblock %}

{% block header %}  
    {{ title|upper }}
{% endblock %} 

{% block content %}

    <h2> {{ text }} </h2>

    <form method='post' class="navbar-form navbar-left">
        {% csrf_token %}
        <div class="form-group">
          {% render_field form.text class="form-control" placeholder="Buscar" %}
          <strong class="text-danger"> {{ form.text.errors }} </strong>
        </div>
        <div class="form-group">
          {% render_field form.fecha class="form-control" placeholder="aaaa" %}
          <strong class="text-danger"> {{ form.fecha.errors }} </strong>
        </div>
        <button type="submit" class="btn btn-success">Buscar</button>
    </form>
        
    {% if object_list %}
        <table class="table table-condensed table-striped">
            <thead>
                <tr>
                    <th>Ciudad</th>
                    <th>Temperatura</th>
                    <th>Fecha</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in object_list %}
                    <tr>
                        <td> {{ obj.id_estacion.id_ciudad.nombre }} </td>
                        <td> {{ obj.tmax }} </td>
                        <td> {{ obj.fecha }} </td>
                    </tr>
                {% endfor%}
            </tbody>
        </table>
    {% endif %}

{% endblock %}

climatologies/templates/weather.html
{% extends 'layout1.html' %}
{% load widget_tweaks %}

{% block title %}
    {{ title }}
{% endblock %}

{% block header %}  
    {{ title|upper }}
{% endblock %} 

{% block content %}
    <canvas id="rain-canvas">
    </canvas>
    <canvas id="cloud-canvas">
    </canvas>
    <canvas id="weather-canvas">
    </canvas>
    <canvas id="time-canvas">
    </canvas>
    <canvas id="lightning-canvas">
    </canvas>
    <div class="page-wrap">
        <header class="search-bar">
            <p class="search-text"><span class="search-location-text">Cual es el clima en su ciudad <input id="search-location-input" class="search-location-input" type="text" placeholder="Ciudad"></span></p>
            <div class="search-location-button-group">
                <button id="search-location-button" class="btn btn-default btn-lg glyphicon glyphicon-search"></button>
                <button id="geo-button" class="btn btn-default btn-lg glyphicon glyphicon-map-marker "></button>
            </div>
        </header>

        <div id="geo-error-message" class="geo-error-message hide"><button id='close-error' class='fa fa-times close-error'></button>¡UH oh! Parece que no podemos encontrar su ubicación. Si está usando un Adblocker, puede bloquear nuestra capacidad de encontrar su ubicación. Por favor, escriba su ciudad en el cuadro de búsqueda de arriba!</div>

        <div id="front-page-description" class="front-page-description middle">
            <h1>Arasunu Clima App</h1>
            <h2>Una app para conocer el clima</h2>
        </div>
        <div class="attribution-links hide" id="attribution-links"><button id='close-attribution' class='fa fa-times close-attribution'></button>
            <h3>Icons from <a href="https://thenounproject.com/">Noun Project</a></h3>
            <ul>
                <li class="icon-attribution"><a href="https://thenounproject.com/term/cloud/6852/">Cloud</a> by Pieter J. Smits</li>
                <li class="icon-attribution"><a href="https://thenounproject.com/term/snow/64/">Snow</a> from National Park Service Collection</li>
                <li class="icon-attribution"><a href="https://thenounproject.com/term/drop/11449/">Drop</a> Alex Fuller</li>
                <li class="icon-attribution"><a href="https://thenounproject.com/term/smoke/27750/">Smoke</a> by Gerardo Martín Martínez</li>
                <li class="icon-attribution"><a href="https://thenounproject.com/term/moon/13554/">Moon</a> by Jory Raphael</li>
                <li class="icon-attribution"><a href="https://thenounproject.com/term/warning/18974/">Warning</a> by Icomatic</li>
                <li class="icon-attribution"><a href="https://thenounproject.com/term/sun/13545/">Sun</a> by Jory Raphael</li>
                <li class="icon-attribution"><a href="https://thenounproject.com/term/windsock/135621/">Windsock</a> by Golden Roof</li>
        </div>
        <div id="weather" class="weather middle hide">
            <div class="location" id="location"></div>
            <div class="weather-container">
                <div id="temperature-info" class="temperature-info">
                    <div class="temperature" id="temperature"></div>
                    <div class="weather-description" id="weather-description"></div>
                </div>
                <div class="weather-box">
                    <ul class="weather-info" id="weather-info">
                        <li class="weather-item humidity">Humedad: <span id="humidity"></span>%</li><!--
                     --><li class="weather-item wind">Viento: <span id="wind-direction"></span> <span id="wind"></span> <span id="speed-unit"></span></li>
                    </ul>
                </div>
                <div class="temp-change">
                    <button id="celsius" class="temp-change-button celsius">&deg;C</button><button id="fahrenheit" class="temp-change-button fahrenheit">&deg;F</button>
                </div>
            </div>
        </div> 
    </div>

{% endblock %}