arasunu/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from climatologies.views import Weather

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('departments.urls', namespace='departments')),
    url(r'^', include('climatologies.urls', namespace='climatologies')),
    url(r'^', include('locations.urls', namespace='locations')),
    url(r'^', include('hydrologies.urls', namespace='hydrologies')),
    url(r'^', Weather, name='weather'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hydrologies/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
        url(r'^api/v4/json/(?P<city>[\w]+)/(?P<month>[0-9]+)/(?P<year>[0-9]+)/$', views.HydroJson, name='HydroJson'),
        url(r'^hydrology/form/$', views.getFormHydro, name='getFormHydro'),
        url(r'^hydrology/ajax/$', views.climaParam1, name='climaParam1'),
        url(r'^hydrology/maps/$', views.viewMap, name='viewMap'),
        url(r'^hydrology/stations/$', views.viewStation, name='viewStation'),
        url(r'^hydrology/stations/auto/$', views.viewStationAuto, name='viewStationAuto'),
]

hydrologies/models.py
# coding=utf-8

from __future__ import unicode_literals

from django.db import models
from locations.models import Location
from stationtypes.models import StationType
from stations.models import Station

class Hydrology(models.Model):
    id_estacion = models.ForeignKey(Location, on_delete=models.CASCADE)
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    id_tipo = models.ForeignKey(StationType, on_delete=models.CASCADE)
    nombre_estacion = models.CharField(max_length=60, blank=True, null=True)
    fecha = models.DateTimeField(blank=True, null=True)
    altura = models.CharField(max_length=10, blank=True, null=True)
    max = models.CharField(max_length=10, blank=True, null=True)
    med = models.CharField(max_length=10, blank=True, null=True)
    min = models.CharField(max_length=10, blank=True, null=True)
    p10 = models.CharField(max_length=10, blank=True, null=True)
    p50 = models.CharField(max_length=10, blank=True, null=True)
    p90 = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return "%s" %(self.nombre_estacion)

    class Meta:
        verbose_name = 'Hidrología'
        verbose_name_plural = 'Hidrologias'

stations/models.py
from __future__ import unicode_literals

from django.db import models
from locations.models import Location
from stationtypes.models import StationType

# Create your models here.

class Station(models.Model):
    name = models.CharField(max_length=240, blank=True, null=True)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    fktypestation = models.ForeignKey(StationType, on_delete=models.CASCADE)
    def __str__(self):
        return "%s %s" %(self.name, self.location.id)

    class Meta:
        verbose_name = 'Estacion'
        verbose_name_plural = 'Estaciones'
        ordering = ('id',)

climatologies/forms.py
from django import forms
from cities.models import City
from datetime import datetime

class FormSearch(forms.Form):
    n = tuple((str(n), str(n)) for n in range(1973, datetime.now().year + 1))
    city_list = City.objects.all().order_by('nombre')
    text = forms.ChoiceField(choices=((x.nombre, x.nombre) for x in city_list ), error_messages={'required': 'Este campo es obligatorio'})
    fecha = forms.ChoiceField(choices=n, error_messages={'required': 'Este campo es obligatorio'})

class FormGraphic(forms.Form):
    city_list = City.objects.all().order_by('nombre')
    c = ((x.nombre, x.nombre) for x in city_list )
    c = tuple([(u'', '------')] + list(c))
    text = forms.ChoiceField(choices=c, error_messages={'required': 'Este campo es obligatorio'})
    n = tuple((str(n), str(n)) for n in range(1973, datetime.now().year + 1))
    months = [('1','Enero'),
                  ('2','Febrero'),
                  ('3','Marzo'),
                  ('4','Abril'),
                  ('5','Mayo'),
                  ('6','Junio'),
                  ('7','Julio'),
                  ('8','Agosto'),
                  ('9','Setiembre'),
                  ('10','Octubre'),
                  ('11','Noviembre'),
                  ('12','Diciembre'),]
    months = tuple([(u'', '------')] + list(months))
    month = forms.ChoiceField(choices=months, error_messages={'required': 'Este campo es obligatorio'})
    n = tuple([(u'', '------')] + list(n))
    year = forms.ChoiceField(choices=n, error_messages={'required': 'Este campo es obligatorio'})

hydrologies/forms.py
# coding=utf-8

from django import forms
from hydrologies.models import Hydrology
from stationtypes.models import StationType
from cities.models import City
from datetime import datetime

class FormHydrology(forms.Form):
    n = tuple((str(n), str(n)) for n in range(1973, datetime.now().year + 1))
    object_list = StationType.objects.all()
    text = forms.ChoiceField(choices=((x.nombre, x.nombre) for x in object_list ), error_messages={'required': 'Este campo es obligatorio'})
    fecha = forms.ChoiceField(choices=n, error_messages={'required': 'Este campo es obligatorio'})
    city_list = City.objects.all().order_by('nombre')
    city = forms.ChoiceField(choices=((x.nombre, x.nombre) for x in city_list ), error_messages={'required': 'Este campo es obligatorio'})

hydrologies/views.py
# -*- coding: utf-8 -*-

from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from climatologies.forms import FormSearch, FormGraphic
from .models import Hydrology
import json
from django.http import JsonResponse
from django.core.serializers.json import Serializer



def getFormHydro(request):
    title = 'Arasunu'
    form = FormGraphic() 
    template = loader.get_template('formhydro.html')
    context = {
        'title': title,
        'form': form,
    }
    return HttpResponse(template.render(context, request))


def climaParam1(request):
    text = request.GET.get('text', None)
    month = request.GET.get('month', None)
    year = request.GET.get('year', None)
    data = {
        'city': text,
        'month': month,
        'year': year
    }
    return HttpResponse(json.dumps(data, ensure_ascii=False, encoding="utf-8"), content_type='application/json')


def HydroJson(request, city, month, year):
    object_list = Hydrology.objects.filter(id_estacion_id__id_ciudad__nombre__icontains=city, fecha__month=month,  fecha__year=year).order_by('fecha')
    data = [{'Letter': int(item.fecha.day), 'Freq': item.max} for item in object_list]
    return HttpResponse(json.dumps(data, ensure_ascii=False, encoding="utf-8"), content_type='application/json')

def viewMap(request):
    title = 'Arasunu'
    template = loader.get_template('risk_zone.html')
    context = {
        'title': title,
    }
    return HttpResponse(template.render(context, request))

def viewStation(request):
    title = 'Arasunu'
    template = loader.get_template('stations.html')
    context = {
        'title': title,
    }
    return HttpResponse(template.render(context, request))

def viewStationAuto(request):
    title = 'Arasunu'
    template = loader.get_template('stations_auto.html')
    context = {
        'title': title,
    }
    return HttpResponse(template.render(context, request))

stations/views.py
from django.shortcuts import render

# Create your views here.

hydrologies/templates/formhydro.html
{% extends 'layout.html' %}
{% load widget_tweaks %}

{% block title %}
    {{ title }}
{% endblock %}

{% block header %}
    {{ title|upper }}
<style>

  .bar{
    fill: steelblue;
  }

  .bar:hover{
    fill: brown;
  }

    .axis {
      font: 10px sans-serif;
    }

    .axis path,
    .axis line {
      fill: none;
      stroke: #000;
      shape-rendering: crispEdges;
    }

</style>
{% endblock %}

{% block javascript %}
<script src="http://d3js.org/d3.v3.min.js"></script>
<script>

    $("#id_text").change(function () {
      console.log( $(this).val() );
    });

    $("#id_year").change(function () {
      console.log( $(this).val() );
    });
    $("#id_month").change(function () {
      console.log( $(this).val() );
    });

    $("#id_year").change(function () {
      $('#result').html('');
      var year = $(this).val();
      var text = $("#id_text").val();
      var month = $('#id_month').val();

      $.ajax({
        url: "{% url 'hydrologies:climaParam1' %}",
        data: {
          'text': text,
          'month': month,
          'year': year
        },
        dataType: 'json',
        success: function (data) {
            data = "http://192.168.1.125/api/v4/json/"+data.city+"/"+data.month+"/"+data.year+"/"
            console.log(data);
            graphic(data);
            }
      });

    });


function graphic(data){

    // set the dimensions of the canvas
    var margin = {top: 20, right: 20, bottom: 70, left: 40},
        width = 600 - margin.left - margin.right,
        height = 300 - margin.top - margin.bottom;


    // set the ranges
    var x = d3.scale.ordinal().rangeRoundBands([0, width], .05);

    var y = d3.scale.linear().range([height, 0]);

    // define the axis
    var xAxis = d3.svg.axis()
        .scale(x)
        .orient("bottom")


    var yAxis = d3.svg.axis()
        .scale(y)
        .orient("left")
        .ticks(10);


    // add the SVG element
    var svg = d3.select("#result").append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom)
      .append("g")
        .attr("transform", 
              "translate(" + margin.left + "," + margin.top + ")");


    // load the data
    d3.json(data, function(error, data) {

        data.forEach(function(d) {
            d.Letter = d.Letter;
            d.Freq = +d.Freq;
        });
        
      // scale the range of the data
      x.domain(data.map(function(d) { return d.Letter; }));
      y.domain([0, d3.max(data, function(d) { return d.Freq; })]);

      // add axis
      svg.append("g")
          .attr("class", "x axis")
          .attr("transform", "translate(0," + height + ")")
          .call(xAxis)
        .selectAll("text")
          .style("text-anchor", "end")
          .attr("dx", "-.8em")
          .attr("dy", "-.55em")
          .attr("transform", "rotate(-90)" );

      svg.append("g")
          .attr("class", "y axis")
          .call(yAxis)
        .append("text")
          .attr("transform", "rotate(-90)")
          .attr("y", 5)
          .attr("dy", ".71em")
          .style("text-anchor", "end")
          .text("Altura");


      // Add bar chart
      svg.selectAll("bar")
          .data(data)
        .enter().append("rect")
          .attr("class", "bar")
          .attr("x", function(d) { return x(d.Letter); })
          .attr("width", x.rangeBand())
          .attr("y", function(d) { return y(d.Freq); })
          .attr("height", function(d) { return height - y(d.Freq); });

    });
}
</script>
{% endblock %}
{% block content %}
  <form method='post' class="navbar-form navbar-left">
      {% csrf_token %}
      <div class="form-group">
        {% render_field form.text class="form-control" %}
        <strong class="text-danger"> {{ form.text.errors }} </strong>
      </div>
      <div class="form-group">
        {% render_field form.month class="form-control" %}
        <strong class="text-danger"> {{ form.month.errors }} </strong>
      </div>
      <div class="form-group">
        {% render_field form.year class="form-control" %}
        <strong class="text-danger"> {{ form.year.errors }} </strong>
      </div>
  </form>
  <div id="result"></div>
{% endblock %}

hydrologies/templates/risk_zone.html
{% extends 'layout.html' %}
{% load widget_tweaks %}


{% block title %}
    {{ title }}
{% endblock %}

{% block header %}
    {{ title|upper }}
{% endblock %}

{% block content %}
    <div id='map'></div>
{% endblock %}

{% block javascript %}
    
    <script>

        var rio = L.layerGroup();
        L.geoJSON(riopy).addTo(rio);
        
        var riesgo = L.layerGroup(); 
        L.geoJSON(zonas, {color: 'red'}).addTo(riesgo);

        var is = L.layerGroup();
        L.geoJSON(islas,{color:'lightgreen'}).addTo(is);



        var mbAttr = 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
        '<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
        'Imagery © <a href="http://mapbox.com">Mapbox</a>',
    mbUrl = 'https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoicnV0aW0iLCJhIjoiMzhmNTJiNjQyZWM3OTNiYTEzNmYwZDhhMjE2Y2QwZGUifQ.5vkZReSc0z5kct3ScjU2FA';

        var grayscale   = L.tileLayer(mbUrl, {id: 'mapbox.light', attribution: mbAttr}),
        streets  = L.tileLayer(mbUrl, {id: 'mapbox.streets',   attribution: mbAttr}),
        satelite = L.tileLayer(mbUrl, {id: 'mapbox.satellite',   attribution: mbAttr});



        var map = L.map('map', {
            center: [-25.2979, -57.6131],
            zoom: 12,
            layers: [grayscale]
        });


        var baseLayers = {
            "Grayscale": grayscale,
            "Streets": streets,
            "Satelite": satelite
        };

        var overlays = {
                "Rio Paraguay": rio,
                "Islas": is,
                "Zonas de Riesgo": riesgo
            };
            
        L.control.layers(baseLayers, overlays).addTo(map);
            map.fitBounds(geoJSON.getBounds());
            

    </script>
{% endblock %}

hydrologies/templates/stations.html
{% extends 'layout.html' %}
{% load widget_tweaks %}


{% block title %}
    {{ title }}
{% endblock %}

{% block header %}
    {{ title|upper }}
{% endblock %}

{% block content %}
    <div id='map'></div>
{% endblock %}

{% block javascript %}

    <script>
        var map = L.map('map').setView([-23.453,-58.447], 6);

        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoicnV0aW0iLCJhIjoiMzhmNTJiNjQyZWM3OTNiYTEzNmYwZDhhMjE2Y2QwZGUifQ.5vkZReSc0z5kct3ScjU2FA', {
            maxZoom: 18,
            attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
                '<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
                'Imagery © <a href="http://mapbox.com">Mapbox</a>',
            id: 'mapbox.light'
        }).addTo(map);


        function onEachFeature(feature, layer) {
            // does this feature have a property named popupContent?
            if (feature.properties && feature.properties.popupContent) {
                layer.bindPopup(feature.properties.popupContent);
            }
        }

        L.geoJSON(geojsonFeature, {
            onEachFeature: onEachFeature
        }).addTo(map);

    </script>    

{% endblock %}

hydrologies/templates/stations_auto.html
{% extends 'layout.html' %}
{% load widget_tweaks %}


{% block title %}
    {{ title }}
{% endblock %}

{% block header %}
    {{ title|upper }}
{% endblock %}

{% block content %}
    <div id='map'></div>
{% endblock %}

{% block javascript %}

   <script>
        var map = L.map('map').setView([-23.453,-58.447], 6);

        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoicnV0aW0iLCJhIjoiMzhmNTJiNjQyZWM3OTNiYTEzNmYwZDhhMjE2Y2QwZGUifQ.5vkZReSc0z5kct3ScjU2FA', {
            maxZoom: 18,
            attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
                '<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
                'Imagery © <a href="http://mapbox.com">Mapbox</a>',
            id: 'mapbox.light'
        }).addTo(map);


        function onEachFeature(feature, layer) {
            // does this feature have a property named popupContent?
            if (feature.properties && feature.properties.popupContent) {
                layer.bindPopup(feature.properties.popupContent);
            }
        }

        L.geoJSON(geojsonFeature, {
            onEachFeature: onEachFeature
        }).addTo(map);

        
        
    </script>

{% endblock %}