arasunu/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from climatologies.views import Weather

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('departments.urls', namespace='departments')),
    url(r'^', include('climatologies.urls', namespace='climatologies')),
    url(r'^', include('locations.urls', namespace='locations')),
    url(r'^', include('hydrologies.urls', namespace='hydrologies')),
    url(r'^', Weather, name='weather'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

climatologies/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^history/$', views.History, name='history'),
    url(r'^api/v1/json/$', views.ClimaJson, name='climaJson'),
    url(r'^api/v2/json/$', views.ClimaJson2, name='climaJson2'),
    url(r'^api/v4/json/$', views.get_cli, name='get_cli'),
    url(r'^api/v3/json/(?P<city>[\w]+)/(?P<month>[0-9]+)/(?P<year>[0-9]+)/$', views.ClimaJson3, name='climaJson3'),
    url(r'^graphic/$', views.Graphic, name='graphic'),
    url(r'^graphic/form/$', views.getForm, name='getForm'),
    url(r'^graphic/form/c3/$', views.getFormc3, name='getFormc3'),
    url(r'^ajax/year/$', views.climaParam, name='climaParam'),
]

hydrologies/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
        url(r'^api/v4/json/(?P<city>[\w]+)/(?P<month>[0-9]+)/(?P<year>[0-9]+)/$', views.HydroJson, name='HydroJson'),
        url(r'^hydrology/form/$', views.getFormHydro, name='getFormHydro'),
        url(r'^hydrology/ajax/$', views.climaParam1, name='climaParam1'),
        url(r'^hydrology/maps/$', views.viewMap, name='viewMap'),
        url(r'^hydrology/stations/$', views.viewStation, name='viewStation'),
        url(r'^hydrology/stations/auto/$', views.viewStationAuto, name='viewStationAuto'),
]

locations/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^api/v1/(?P<pk>[0-9]+)/$', views.locationJson, name='locationJson' ),
    url(r'^api/v4/$', views.listLocationJson, name='listLocationJson' ),
    url(r'^api/v5/$', views.getLocation, name='getLocation' ),
    url(r'^maps/$', views.viewMap, name='viewMap' ),
]

templates/layout.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="es">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=divice-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <link rel="stylesheet" href="{% static 'css/ol.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css" integrity="sha512-M2wvCLH6DSRazYeZRIm1JnYyh22purTM+FDB5CsyxtQJYeKq83arPe5wgbNmcFXGqiSH2XR8dT/fJISVA1r/zQ==" crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.2.0/dist/leaflet.js" integrity="sha512-lInM/apFSqyy1o6s89K4iQUKg6ppXEgsVxT35HbzUupEVRh2Eu9Wdl4tHj7dZO0s1uvplcYGmt3498TtHq+log==" crossorigin=""></script>
    <!--<link rel="stylesheet" href="{% static 'css/c3.css' %}">-->
    <title> {% block title %}  {% endblock %} </title>
</head>
<body id="weather-background" class="default-weather">
    <section class="container">
        <header>
            <div class="page-header">
                <h4> {% block header %}  {% endblock %} </h4>
            </div>
            {# % if user.is_authenticated % #}
            <nav class="navbar navbar-inverse" role="navigation">
              <!-- El logotipo y el icono que despliega el menú se agrupan
                   para mostrarlos mejor en los dispositivos móviles -->
              <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse"
                        data-target=".navbar-ex1-collapse">
                  <span class="sr-only">Desplegar navegación</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'weather' %}">Inicio</a>
              </div>
             
              <!-- Agrupar los enlaces de navegación, los formularios y cualquier
                   otro elemento que se pueda ocultar al minimizar la barra -->
              <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Historicos <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url 'climatologies:getForm' %}">Climatología</a></li>
                      <li><a href="{% url 'hydrologies:getFormHydro' %}">Hidrología</a></li>
                    </ul>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Crecidas <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url 'hydrologies:viewMap' %}">Listar</a></li>
                      <li><a href="{% url 'hydrologies:viewStation' %}">Estaciones</a></li>
                      <li><a href="{% url 'hydrologies:viewStationAuto' %}">Estaciones Automaticas</a></li>
                    </ul>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Estadisticas <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><a href="">Listar</a></li>
                    </ul>
                  </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                   <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Login
                    </a>
                  </li>
                </ul>
              </div>
            </nav>
            {# % endif % #}
        </header>

        {% block content %}{% endblock %}
    </section>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/rioPy.js' %}"></script>
    <script src="{% static 'js/zonas.js' %}"></script>
    <script src="{% static 'js/islas.js' %}"></script>
    <script src="{% static 'js/estaciones.js' %}"></script>
    <script src="{% static 'js/estacionesAutomaticas.js' %}"></script>
    {% block javascript %}{% endblock %}
    <!--<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>-->
    <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
    <!--<script src="{% static 'js/c3.js' %}"></script>
    <script src="https://www.gstatic.com/firebasejs/3.4.0/firebase.js"></script>-->
</body>
</html>

templates/layout1.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="es">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=divice-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/weather.css' %}">
    <title> {% block title %}  {% endblock %} </title>
</head>
<body id="weather-background" class="default-weather">
    <section class="container">
        <header>
            <div class="page-header">
                <h4> {% block header %}  {% endblock %} </h4>
            </div>
            {# % if user.is_authenticated % #}
            <nav class="navbar navbar-inverse" role="navigation">
              <!-- El logotipo y el icono que despliega el menú se agrupan
                   para mostrarlos mejor en los dispositivos móviles -->
              <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse"
                        data-target=".navbar-ex1-collapse">
                  <span class="sr-only">Desplegar navegación</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'weather' %}">Inicio</a>
              </div>
             
              <!-- Agrupar los enlaces de navegación, los formularios y cualquier
                   otro elemento que se pueda ocultar al minimizar la barra -->
              <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Historicos <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url 'climatologies:getForm' %}">Climatología</a></li>
                      <li><a href="{% url 'hydrologies:getFormHydro' %}">Hidrología</a></li>
                    </ul>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Crecidas <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url 'hydrologies:viewMap' %}">Listar</a></li>
                      <li><a href="{% url 'hydrologies:viewStation' %}">Estaciones</a></li>
                      <li><a href="{% url 'hydrologies:viewStationAuto' %}">Estaciones Automaticas</a></li>
                    </ul>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Estadisticas <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><a href="">Listar</a></li>
                    </ul>
                  </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                   <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Login
                    </a>
                  </li>
                </ul>
              </div>
            </nav>
            {# % endif % #}
        </header>

        {% block content %}{% endblock %}
    </section>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/weather.js' %}"></script>
    
</body>
</html>